### ISSUE TITLE
MPL 2.0 第3.5節の一部が未訳出

### ISSUE THREAD

**Issue by Guest126** [opensource-jp/licenses#8]
第3.5節において MPL 2.0 で追加された最後の一節

> You may include additional disclaimers of warranty and limitations of liability specific to any jurisdiction.

に対応する翻訳文が存在しないようです。

**Comment by shujisado** [comment]
抜け落ちてましたね。修正しました。

b2691fea4c6e9fe20c14f828ce687e2783a4c440
